<a href="https://colab.research.google.com/github/sarabehnamian/DNAs-age/blob/main/Copy_of_Untitled2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas sklearn matplotlib

Requirement already satisfied: pandas in /usr/local/lib/python3.6/dist-packages (1.1.5)
Requirement already satisfied: sklearn in /usr/local/lib/python3.6/dist-packages (0.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.6/dist-packages (3.2.2)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.6/dist-packages (from pandas) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas) (2018.9)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.6/dist-packages (from pandas) (1.19.4)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.6/dist-packages (from sklearn) (0.22.2.post1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib) (1.3.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib) (2.4.7)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.6/dist-packages (from matplotlib) (0.10.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.6/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.6/dist-packages (from scikit-learn->sklearn) (1.0.0)
Requirement already satisfied: scipy>=0.17.0 in /usr/local/lib/python3.6/dist-packages (from scikit-learn->sklearn) (1.4.1)

In [ ]:
 import pandas

In [ ]:
df = pandas.read_excel('Dataset.xlsx')

FileNotFoundError: ignored

In [ ]:
df

            ID        Country  ...  ModernComponent3   DateBP
0       12885A  UnitedKingdom  ...          0.000010   1165.0
1       NO3423  UnitedKingdom  ...          0.005305   1170.0
2      RISE568  CzechRepublic  ...          0.008402   1200.0
3       12881A  UnitedKingdom  ...          0.025458   1232.0
4      RISE569  CzechRepublic  ...          0.008809   1235.0
..         ...            ...  ...               ...      ...
940      I1690         Israel  ...          0.000010  12750.0
941  Rochedane         France  ...          0.016300  12960.0
942       SATP        Georgia  ...          0.000010  13256.0
943      I1687         Israel  ...          0.000010  13265.0
944     Bichon    Switzerland  ...          0.004967  13665.0

[945 rows x 11 columns]

In [ ]:
y = df['DateBP'].copy()

In [ ]:
y

0       1165.0
1       1170.0
2       1200.0
3       1232.0
4       1235.0
        ...
940    12750.0
941    12960.0
942    13256.0
943    13265.0
944    13665.0
Name: DateBP, Length: 945, dtype: float64

In [ ]:
del df['DateBP']

In [ ]:
del df['ID']

In [ ]:
from sklearn.neighbors import KNeighborsRegressor

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
knn = KNeighborsRegressor()

In [ ]:
country = df['Country']

In [ ]:
import pandas as pd

In [ ]:
dummies = pd.get_dummies(df['Country'], prefix='country')

In [ ]:
df1 = pd.concat([dummies, df], axis=1)

In [ ]:
df1

     country_Armenia  country_Austria  ...  ModernComponent2  ModernComponent3
0                  0                0  ...          0.994777          0.000010
1                  0                0  ...          0.612849          0.005305
2                  0                0  ...          0.671613          0.008402
3                  0                0  ...          0.770237          0.025458
4                  0                0  ...          0.773653          0.008809
..               ...              ...  ...               ...               ...
940                0                0  ...          0.000010          0.000010
941                0                0  ...          0.255682          0.016300
942                0                0  ...          0.039922          0.000010
943                0                0  ...          0.000010          0.000010
944                0                0  ...          0.183017          0.004967

[945 rows x 43 columns]

In [ ]:
del df1['Country']

In [ ]:
df1

     country_Armenia  country_Austria  ...  ModernComponent2  ModernComponent3
0                  0                0  ...          0.994777          0.000010
1                  0                0  ...          0.612849          0.005305
2                  0                0  ...          0.671613          0.008402
3                  0                0  ...          0.770237          0.025458
4                  0                0  ...          0.773653          0.008809
..               ...              ...  ...               ...               ...
940                0                0  ...          0.000010          0.000010
941                0                0  ...          0.255682          0.016300
942                0                0  ...          0.039922          0.000010
943                0                0  ...          0.000010          0.000010
944                0                0  ...          0.183017          0.004967

[945 rows x 42 columns]

In [ ]:
X_train, X_test, y_train, y_test=train_test_split(df1, y, test_size=.25)

In [ ]:
knn.fit(X_train, y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                    weights='uniform')

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score

In [ ]:
import math

In [ ]:
math.sqrt(mean_squared_error(y_test, knn.predict(X_test)))

1162.6755988968039

In [ ]:
r2_score(y_test, knn.predict(X_test))

0.7130893262800639

In [ ]:
print('Differece between real and predicted age in the training samples')

Differece between real and predicted age in the training samples

In [ ]:
print('Difference between real age and predicted age in the non-training samples')

Difference between real age and predicted age in the non-training samples

In [ ]:
sum(abs(y_test-knn.predict(X_test)))/len(y_test)

668.0590717299577